In [ ]:
# Load cluster
import pandas as pd
import numpy as np

df = pd.read_parquet( "../logs/classification/test_scored_gen1.parquet" )

print( "(Rows, Columns)" )
print( df.shape )

(Rows, Columns)
(147236, 121)

In [22]:
rf_top = df.nlargest(50, "rf_probability")

rf_top[
    [
        "ticker",
        "date",
        "rf_probability",
        "future_excess_5y",
        "beats_market_5y"
    ]
]

       ticker       date  rf_probability  future_excess_5y  beats_market_5y
97301    DIOD 2020-11-17        0.506980         -1.299951                0
97302    DIOD 2020-11-24        0.503858         -1.270620                0
97303    DIOD 2020-12-02        0.503091         -1.332196                0
92358    AVGO 2020-12-02        0.501440          8.710680                1
113822   SMTC 2020-11-24        0.498061         -1.017250                0
113821   SMTC 2020-11-17        0.496559         -1.032594                0
113823   SMTC 2020-12-02        0.493821         -0.928890                0
29275     ADI 2020-12-02        0.493519          0.080045                1
97296    DIOD 2020-10-13        0.493013         -1.230743                0
97300    DIOD 2020-11-10        0.492641         -1.327118                0
115321   MKSI 2020-12-02        0.491031         -0.858198                0
92345    AVGO 2020-08-31        0.488996          8.026721                1
97297    DIOD 2020-10-20        0.488794         -1.202145                0
29273     ADI 2020-11-17        0.487854         -0.110415                0
92351    AVGO 2020-10-13        0.486286          7.520939                1
97295    DIOD 2020-10-06        0.486136         -1.265298                0
77711    KLAC 2020-11-17        0.485723          2.943111                1
97298    DIOD 2020-10-27        0.485637         -1.204760                0
128407    FIS 2020-08-03        0.485411         -1.473146                0
92359    AVGO 2020-12-09        0.484688          8.783875                1
92357    AVGO 2020-11-24        0.483729          7.758741                1
92350    AVGO 2020-10-06        0.482706          8.258738                1
92347    AVGO 2020-09-15        0.482688          8.980121                1
77713    KLAC 2020-12-02        0.482296          2.775119                1
115306   MKSI 2020-08-17        0.482249         -1.197496                0
29274     ADI 2020-11-24        0.481430         -0.092587                0
77710    KLAC 2020-11-10        0.481361          3.608737                1
77712    KLAC 2020-11-24        0.480996          2.682051                1
92356    AVGO 2020-11-17        0.480988          8.069337                1
92348    AVGO 2020-09-22        0.480778          8.500391                1
92342    AVGO 2020-08-10        0.480387          8.435862                1
92352    AVGO 2020-10-20        0.480323          8.292857                1
92344    AVGO 2020-08-24        0.480138          7.783081                1
117144    ESE 2020-11-24        0.479814          0.178371                1
92360    AVGO 2020-12-16        0.479785          6.975927                1
29276     ADI 2020-12-09        0.479668          0.149503                1
92346    AVGO 2020-09-08        0.479156          8.682589                1
115305   MKSI 2020-08-10        0.479125         -1.182495                0
115307   MKSI 2020-08-24        0.478511         -1.140658                0
113820   SMTC 2020-11-10        0.478294         -0.906242                0
97299    DIOD 2020-11-03        0.478107         -1.273144                0
38126    AMAT 2020-08-10        0.478044          0.912282                1
70718     ACN 2020-12-02        0.477384         -0.881627                0
97294    DIOD 2020-09-29        0.477238         -1.173070                0
89234     BMI 2020-12-02        0.476397          0.208235                1
113807   SMTC 2020-08-10        0.475755         -1.171686                0
77707    KLAC 2020-10-20        0.475359          3.614277                1
89235     BMI 2020-12-09        0.475191          0.114740                1
70717     ACN 2020-11-24        0.475037         -0.863941                0
123428    TDY 2020-11-17        0.475018         -0.727041                0

In [23]:
rf_top10 = (
    df.sort_values("rf_probability", ascending=False)
      .head(int(len(df)*0.10))
)

rf_top10["ticker"].value_counts().head(50)

ticker
MSI      51
CIEN     51
VRSK     51
FAST     51
WOLTF    51
BAH      51
UNP      51
CP       51
AME      51
GGG      51
DOV      51
SPXSF    51
ITOCF    51
TMTNF    51
IEX      51
TT       51
J        51
MSA      51
EXPO     51
TRI      51
CSX      51
CTAS     51
WTKWY    51
NSC      51
GPN      51
FSS      51
CBZ      51
ROCK     51
KAI      51
SPXC     51
KFRC     51
TTC      51
TDG      51
POOL     51
CAT      51
MMTRS    51
ROK      51
HEI-A    51
RBC      51
PH       51
DSGR     51
HEI      51
RTO      50
RKLIF    50
LII      50
LSTR     50
TTEK     50
ITT      50
FELE     50
AVGO     49
Name: count, dtype: int64

In [25]:
stock_summary = (
    rf_top10.groupby("ticker")
    .agg(
        times_selected=("ticker", "count"),
        avg_probability=("rf_probability", "mean"),
        median_probability=("rf_probability", "median"),
        avg_future_return=("future_excess_5y", "mean"),
        median_future_return=("future_excess_5y", "median"),
        beat_rate=("beats_market_5y", "mean"),
    )
)

stock_summary.sort_values(
    ["beat_rate", "avg_future_return"],
    ascending=False
).head(50)

,times_selected,avg_probability,median_probability,avg_future_return,median_future_return,beat_rate
ticker,,,,,,
DAC,2,0.349504,0.349504,27.122490,27.122490,1.0
STRL,46,0.364614,0.362653,21.076381,19.840425,1.0
FIX,36,0.363684,0.362607,16.774466,17.129310,1.0
ARLP,8,0.351913,0.353600,10.031317,10.118173,1.0
SM,20,0.382584,0.383659,9.724531,9.462973,1.0
HNRG,25,0.398899,0.414333,9.583763,8.341658,1.0
IESC,49,0.370224,0.369416,9.331105,9.145462,1.0
AVGO,49,0.442451,0.444127,7.607263,7.836940,1.0
ADTTF,44,0.369617,0.369866,7.082214,6.555784,1.0
TDW,20,0.392577,0.395449,6.042838,6.068828,1.0
AXON,18,0.358376,0.355090,5.681881,6.051778,1.0
EDN,41,0.377171,0.378240,5.499699,5.344706,1.0
EME,19,0.358576,0.352264,5.376236,5.199075,1.0
FTI,9,0.351681,0.351679,5.175989,4.587781,1.0
STX,37,0.374361,0.365787,5.150762,4.147693,1.0
PWR,44,0.368870,0.365264,5.014660,4.845649,1.0
ATEYY,27,0.369619,0.364298,4.958320,4.997789,1.0
WLFC,16,0.376510,0.376863,4.837014,4.850561,1.0
EMO,1,0.349021,0.349021,4.675597,4.675597,1.0
YPF,18,0.363346,0.363284,4.389534,3.935516,1.0
JBL,20,0.377103,0.379734,4.184338,4.411252,1.0
FN,44,0.394012,0.389808,4.149745,4.142212,1.0
CAMT,24,0.391476,0.394544,4.141026,4.108569,1.0
MLI,3,0.350574,0.349937,4.086323,4.028371,1.0
GLNG,4,0.357912,0.360990,4.076083,4.112931,1.0
SKT,4,0.344957,0.344780,3.885041,3.923493,1.0
LLY,29,0.382141,0.379756,3.659015,3.434844,1.0
DRS,28,0.371429,0.371776,3.643524,3.977948,1.0
KLAC,43,0.420824,0.434344,3.641748,3.533881,1.0
CPRX,6,0.362327,0.366062,3.606179,3.577171,1.0
WCPRF,9,0.364844,0.361202,3.394381,3.321928,1.0
FNMAS,2,0.349164,0.349164,3.355752,3.355752,1.0
RRC,14,0.367357,0.363821,3.319969,3.512035,1.0
NVMI,38,0.395613,0.404116,3.306649,3.352654,1.0
MU,46,0.385600,0.378222,3.290305,2.125588,1.0
FMCKJ,2,0.349274,0.349274,3.263391,3.263391,1.0
MTDR,2,0.345335,0.345335,3.236978,3.236978,1.0
STNG,20,0.386601,0.386516,3.070315,2.827734,1.0
FNMFN,1,0.352868,0.352868,2.991733,2.991733,1.0
CVE,2,0.348595,0.348595,2.936353,2.936353,1.0
NOG,20,0.374594,0.379714,2.872989,2.982930,1.0
OII,20,0.383054,0.387260,2.768743,2.416054,1.0
MYRG,30,0.352975,0.350817,2.723484,2.678953,1.0
TK,20,0.388628,0.389319,2.700923,2.497092,1.0
FNMAT,2,0.349561,0.349561,2.643398,2.643398,1.0
FNMAN,2,0.351223,0.351223,2.609789,2.609789,1.0
CW,2,0.350104,0.350104,2.596839,2.596839,1.0
APH,37,0.376759,0.380803,2.507835,2.460465,1.0
TNK,11,0.359218,0.358747,2.475394,2.223868,1.0
FNMAJ,2,0.351231,0.351231,2.465071,2.465071,1.0