# Consistent Stock Selection Portfolio

## Goal

This notebook help evaluate if a stock that the model consistently selects performs better then the S&P 500.

While the Random Forest model had performance better than random, it did not have enough to have returns better than S&P 500. This notebook focuses on stocks with repeated high probabilities in order to find more consistently good stocks.

## 1. Load Model Predictions

The classifier output contains:

* Ticker
* Date of Window
* Model Probabilities
* Model Predictions
* Data features
* Weather the stock beat the S&P 500

In [ ]:
# Importing File
import pandas as pd
import numpy as np
import yfinance as yf

# Parameters
SCORED_FILE = "../logs/classification/test_scored_gen1.parquet"

TOP_N = 10
MIN_SELECTIONS = 10
PORTFOLIO_SIZE = 20

df = pd.read_parquet( SCORED_FILE )

df = df.reset_index()

# Test print of (Rows, Columns)
df.shape

(147236, 122)

,index,date,ticker,price,beta_1y,alpha_1y,sector,quote_type,log_market_cap,pe,...,risk_adjusted_5y,sector_is_strong,sector_is_trending,sector_high_breadth,quality_score,beats_market_5y,logreg_probability,logreg_prediction,rf_probability,rf_prediction
0,0,2020-07-06,EGHT,15.98,1.640449,-0.033117,Technology,EQUITY,21.541141,1480.114852,...,0.076579,True,False,False,0,0,0.331555,0,0.340725,0
1,1,2020-07-13,EGHT,15.52,1.631050,-0.034542,Technology,EQUITY,21.511933,1437.508375,...,0.101426,True,False,False,0,0,0.319037,0,0.335861,0
2,2,2020-07-20,EGHT,16.93,1.625617,0.054172,Technology,EQUITY,21.598891,1568.106734,...,0.117621,True,False,True,0,0,0.359690,0,0.346215,0
3,3,2020-07-27,EGHT,16.42,1.624197,0.016425,Technology,EQUITY,21.568304,1520.869003,...,0.104128,True,False,False,0,0,0.331006,0,0.337873,0
4,4,2020-08-03,EGHT,16.25,1.629430,0.013561,Technology,EQUITY,21.557896,1505.123093,...,0.080650,True,False,True,0,0,0.345362,0,0.342717,0

## 2. Identify Top Model Picks

For each predition date, the stocks with the highest model confience are selected. These represent the stocks the model would have purchased at each time window.

In [ ]:
# Get top N highest RF probabilities
top_picks = (
    df.sort_values(
        ["date", "rf_probability"],
        ascending=[True, False]
    )
    .groupby("date")
    .head(TOP_N)
)

top_picks.head()

,index,date,ticker,price,beta_1y,alpha_1y,sector,quote_type,log_market_cap,pe,...,risk_adjusted_5y,sector_is_strong,sector_is_trending,sector_high_breadth,quality_score,beats_market_5y,logreg_probability,logreg_prediction,rf_probability,rf_prediction
115300,115300,2020-07-06,MKSI,111.151100,1.794942,0.010785,Technology,EQUITY,22.739182,21.972115,...,0.785387,True,False,False,3,0,0.357134,0,0.467851,0
92337,92337,2020-07-06,AVGO,28.075953,1.615283,0.001960,Technology,EQUITY,25.617918,5.077504,...,0.579143,True,False,False,3,1,0.352905,0,0.460608,0
38121,38121,2020-07-06,AMAT,60.241611,1.729459,0.031159,Technology,EQUITY,24.590906,5.354276,...,0.908165,True,False,False,3,1,0.354921,0,0.456200,0
84448,84448,2020-07-06,FICO,416.850006,1.766286,-0.013949,Technology,EQUITY,22.991997,12.458078,...,1.306724,True,False,False,3,1,0.381020,0,0.454755,0
77692,77692,2020-07-06,KLAC,19.084976,1.631847,0.027378,Technology,EQUITY,23.939347,4.974626,...,1.185625,True,False,False,3,1,0.350392,0,0.453493,0

## 3. Measure Stock Consistency

How often a stock is selected is then counted. Maximum for this is 51, as there are 51 possible time windows.

Stocks selected repeatedly represent stronger model conviction.

In [ ]:
# Sort stocks by number of times selected
consistent = (
    top_picks
    .groupby("ticker")
    .agg(
        times_selected=("ticker", "count"),
        avg_probability=("rf_probability", "mean"),
        median_probability=("rf_probability", "median"),
        avg_future_return=("future_excess_5y", "mean"),
        median_future_return=("future_excess_5y", "median"),
        beat_rate=("beats_market_5y", "mean")
    )
    .sort_values(
        "times_selected",
        ascending=False
    )
)

consistent.head(50)

,times_selected,avg_probability,median_probability,avg_future_return,median_future_return,beat_rate
ticker,,,,,,
AVGO,31,0.463374,0.467906,7.782043,7.836940,1.000000
TXN,24,0.446163,0.445278,-0.410822,-0.484456,0.083333
ACN,23,0.445970,0.443433,-1.012741,-0.981327,0.000000
KLAC,19,0.467379,0.469013,3.033359,2.775119,1.000000
DIOD,18,0.474531,0.477672,-1.200443,-1.228786,0.000000
ADI,18,0.459058,0.461986,0.176064,0.092871,0.833333
CP,17,0.431363,0.432161,-0.742496,-0.694214,0.000000
FIS,15,0.458876,0.462578,-1.524785,-1.491656,0.000000
MSI,15,0.451964,0.450089,0.448461,0.266082,1.000000
TMTNF,14,0.423895,0.425401,0.213857,0.242535,0.928571
BR,13,0.451298,0.452613,-0.271580,-0.264771,0.076923
SMTC,13,0.473381,0.474314,-1.016311,-0.983245,0.000000
FICO,13,0.451178,0.451299,1.568426,1.499520,1.000000
STM,12,0.463158,0.464483,-1.136008,-1.188110,0.000000
TDY,11,0.447010,0.443994,-0.431978,-0.363864,0.000000
UNP,11,0.430953,0.429787,-0.594837,-0.521799,0.000000
TRI,11,0.423441,0.427069,-0.718817,-0.719505,0.000000
GRMN,10,0.440040,0.440503,0.005420,-0.023910,0.400000
ITOCF,10,0.424043,0.424443,-1.386950,-1.374295,0.000000
WOLTF,10,0.427553,0.427692,-0.763942,-0.726785,0.000000
DOV,9,0.426393,0.427631,-0.270584,-0.297856,0.000000
SPXSF,9,0.425923,0.422625,-1.255907,-1.265126,0.000000
MKSI,9,0.469402,0.474539,-1.158553,-1.181173,0.000000
BMI,9,0.465983,0.470002,0.331806,0.301545,1.000000
AME,9,0.427673,0.429069,-0.021811,-0.005179,0.444444
LRCX,7,0.456504,0.456644,1.560370,1.710499,1.000000
DSGX,7,0.439981,0.433882,-0.475397,-0.354460,0.000000
GGG,7,0.431144,0.432733,-0.743285,-0.757755,0.000000
AMAT,6,0.462806,0.469212,0.921196,0.901586,1.000000
J,6,0.418318,0.416897,-0.389325,-0.403802,0.000000
TYL,6,0.464456,0.465888,-0.920579,-0.940046,0.000000
AAON,6,0.427828,0.430832,-0.027108,-0.056081,0.333333
FAST,5,0.435270,0.432562,0.109301,0.130593,0.600000
MTD,5,0.425666,0.426074,-0.915859,-0.874207,0.000000
A,5,0.425138,0.425617,-0.958072,-0.978118,0.000000
IEX,5,0.427428,0.429701,-0.822228,-0.845732,0.000000
CIEN,5,0.438903,0.437939,6.478181,6.146919,1.000000
ESE,5,0.458454,0.468469,0.230036,0.178371,1.000000
RTO,5,0.430046,0.428851,-0.994954,-0.992775,0.000000
TT,4,0.413701,0.413371,1.297586,1.301724,1.000000
HNRG,4,0.424901,0.423796,10.165645,9.679165,1.000000
ADSK,4,0.457781,0.459420,-0.862381,-0.831253,0.000000
FSS,4,0.414562,0.413947,1.416335,1.388254,1.000000
ENTG,4,0.439705,0.437904,-0.784076,-0.779523,0.000000
MLAB,4,0.453630,0.454980,-1.818501,-1.828508,0.000000
MSA,4,0.424877,0.424301,-0.774724,-0.750982,0.000000
BAH,3,0.433710,0.432618,-0.844312,-0.846982,0.000000
ICLR,3,0.427093,0.427529,-1.396538,-1.422051,0.000000
MPWR,3,0.444337,0.444394,0.894720,0.849231,1.000000
SONY,3,0.443069,0.443928,-0.332750,-0.247393,0.000000

## 4. Filter stocks below threshold

A list of stocks have have been selected at or above the threshold are selected. Stocks only selected by the algorithm a few times are discarded as inconsistent.

In [ ]:
# Filter to stocks have have been selected at, or above, limit
consistent_stocks = (
    consistent[
        consistent["times_selected"] >= MIN_SELECTIONS
    ]
)

consistent_stocks

,times_selected,avg_probability,median_probability,avg_future_return,median_future_return,beat_rate
ticker,,,,,,
AVGO,31,0.463374,0.467906,7.782043,7.836940,1.000000
TXN,24,0.446163,0.445278,-0.410822,-0.484456,0.083333
ACN,23,0.445970,0.443433,-1.012741,-0.981327,0.000000
KLAC,19,0.467379,0.469013,3.033359,2.775119,1.000000
DIOD,18,0.474531,0.477672,-1.200443,-1.228786,0.000000
ADI,18,0.459058,0.461986,0.176064,0.092871,0.833333
CP,17,0.431363,0.432161,-0.742496,-0.694214,0.000000
FIS,15,0.458876,0.462578,-1.524785,-1.491656,0.000000
MSI,15,0.451964,0.450089,0.448461,0.266082,1.000000
TMTNF,14,0.423895,0.425401,0.213857,0.242535,0.928571
BR,13,0.451298,0.452613,-0.271580,-0.264771,0.076923
SMTC,13,0.473381,0.474314,-1.016311,-0.983245,0.000000
FICO,13,0.451178,0.451299,1.568426,1.499520,1.000000
STM,12,0.463158,0.464483,-1.136008,-1.188110,0.000000
TDY,11,0.447010,0.443994,-0.431978,-0.363864,0.000000
UNP,11,0.430953,0.429787,-0.594837,-0.521799,0.000000
TRI,11,0.423441,0.427069,-0.718817,-0.719505,0.000000
GRMN,10,0.440040,0.440503,0.005420,-0.023910,0.400000
ITOCF,10,0.424043,0.424443,-1.386950,-1.374295,0.000000
WOLTF,10,0.427553,0.427692,-0.763942,-0.726785,0.000000

## 5. Limit number of stocks selected

The number of consistently selected stocks are capped to ensure both selection of the best results as well as keeping a simple portfolio.

In [ ]:
# Filter stocks down to maximum number
portfolio = (
    consistent_stocks
    .sort_values(
        [
            "times_selected",
            "avg_probability"
        ],
        ascending=False
    )
    .head(PORTFOLIO_SIZE)
)

portfolio[
    [
        "times_selected",
        "avg_probability",
        "avg_future_return",
        "median_future_return",
        "beat_rate"
    ]
]

,times_selected,avg_probability,avg_future_return,median_future_return,beat_rate
ticker,,,,,
AVGO,31,0.463374,7.782043,7.836940,1.000000
TXN,24,0.446163,-0.410822,-0.484456,0.083333
ACN,23,0.445970,-1.012741,-0.981327,0.000000
KLAC,19,0.467379,3.033359,2.775119,1.000000
DIOD,18,0.474531,-1.200443,-1.228786,0.000000
ADI,18,0.459058,0.176064,0.092871,0.833333
CP,17,0.431363,-0.742496,-0.694214,0.000000
FIS,15,0.458876,-1.524785,-1.491656,0.000000
MSI,15,0.451964,0.448461,0.266082,1.000000
TMTNF,14,0.423895,0.213857,0.242535,0.928571
SMTC,13,0.473381,-1.016311,-0.983245,0.000000
BR,13,0.451298,-0.271580,-0.264771,0.076923
FICO,13,0.451178,1.568426,1.499520,1.000000
STM,12,0.463158,-1.136008,-1.188110,0.000000
TDY,11,0.447010,-0.431978,-0.363864,0.000000
UNP,11,0.430953,-0.594837,-0.521799,0.000000
TRI,11,0.423441,-0.718817,-0.719505,0.000000
GRMN,10,0.440040,0.005420,-0.023910,0.400000
WOLTF,10,0.427553,-0.763942,-0.726785,0.000000
ITOCF,10,0.424043,-1.386950,-1.374295,0.000000

In [ ]:
# Most current window of data
last_date = df["date"].max()

print(last_date)

2021-07-01 00:00:00

## 6. Generate Portfolio List

A list of the top stocks.

This could be expanded to include features of the stocks, either for the most current window or an average over all windows.

In [ ]:
#Tickers for all stocks in portfolio
holdings = portfolio.index.tolist()

holdings

['AVGO',
 'TXN',
 'ACN',
 'KLAC',
 'DIOD',
 'ADI',
 'CP',
 'FIS',
 'MSI',
 'TMTNF',
 'SMTC',
 'BR',
 'FICO',
 'STM',
 'TDY',
 'UNP',
 'TRI',
 'GRMN',
 'WOLTF',
 'ITOCF']

In [49]:
buy_and_hold = df[
    (df["date"] == last_date) &
    (df["ticker"].isin(holdings))
].copy()

buy_and_hold[
    [
        "ticker",
        "rf_probability",
        "future_excess_5y",
        "beats_market_5y"
    ]
]

       ticker  rf_probability  future_excess_5y  beats_market_5y
16471      CP        0.410044         -0.688673                0
29304     ADI        0.422538          0.648811                1
32574   TMTNF        0.405139          0.176961                1
38273     MSI        0.444481          0.178112                1
62077      BR        0.358905         -0.909200                0
70747     ACN        0.435611         -1.383258                0
77742    KLAC        0.357921          7.129102                1
79903     TRI        0.414366         -0.912384                0
84498    FICO        0.386459          0.557984                1
86167     UNP        0.415770         -0.462905                0
92387    AVGO        0.440227          6.784705                1
93050   ITOCF        0.368118         -1.382037                0
97332    DIOD        0.389930         -0.522250                0
100341    TXN        0.448336         -0.051347                0
103804   GRMN        0.446010         -0.043109                0
106418    STM        0.382552          0.170455                1
113852   SMTC        0.344321          0.306527                1
123459    TDY        0.406761         -0.284345                0
125652  WOLTF        0.415202         -1.060878                0
128453    FIS        0.315468         -1.531920                0

In [ ]:
spy = yf.download(
    "SPY",
    start=last_date,
    end=pd.Timestamp(last_date) + pd.DateOffset(years=5),
    auto_adjust=True
)

# Result Summary

The excess returns (return above SPY) and actual returns are both calculated.

For easier understanding, a simulation is also run, based on a $10,000 investment, equally distributed to each stock.

The results suggest that repeated model selection is useful as an investment signal.

In [ ]:
portfolio_return = buy_and_hold["future_ret_5y"].mean()
portfolio_excess = buy_and_hold["future_excess_5y"].mean()

print(
    f"Portfolio excess return: {portfolio_excess:.2%}"
)

print(
    f"Portfolio return: {portfolio_return:.2%}"
)

spy_return = (
    spy["Close"].iloc[-1].item() /
    spy["Close"].iloc[0].item()
    - 1
)

initial_investment = 10000

spy_value = initial_investment * (1 + spy_return)

ending_value = (
    initial_investment *
    (1 + portfolio_return)
)

print(
    "\n",
    "---Portfolio simulation ---",
)

print(
    f"Starting value: ${initial_investment:,.2f}"
)

print(
    f"SPY Ending value: ${spy_value:,.2f}"
)

print(
    f"Model Ending value: ${ending_value:,.2f}"
)

return_difference = ( ending_value - spy_value ) / spy_value

print(
    f"Different compared to SPY: {return_difference:+.2%}"
)

Portfolio excess return: 33.60%
Portfolio return: 118.98%

 ---Portfolio simulation ---
Starting value: $10,000.00
SPY Ending value: $18,562.83
Model Ending value: $21,897.90
Different compared to SPY: +17.97%