In [52]:
MAX_DEPTH = 1
BEST_CLUSTER = 6

In [53]:
# Load cluster

import pandas as pd
import numpy as np

df = pd.read_parquet(
    f"../logs/kmean/clustered_data_gen1_depth{MAX_DEPTH}.parquet"
)

# Outputs rows, columns
df.shape

(8821, 112)

In [54]:
# Quick summary of cluster composition
cluster_summary = df.groupby("cluster").agg(
    rows=("ticker", "count"),
    unique_tickers=("ticker", "nunique"),
    unique_sectors=("sector", "nunique")
)

# Add number of rows per year
year_counts = (
    df.assign(year=df["date"].dt.year)
      .groupby(["cluster", "year"])
      .size()
      .unstack(fill_value=0)
)

# Combine
cluster_summary = cluster_summary.join(year_counts)

cluster_summary.sort_values("rows", ascending=False)

         rows  unique_tickers  unique_sectors  2020
cluster
6        1947            1947               7  1947
7        1644            1644               5  1644
2        1632            1632               7  1632
4        1068            1068               3  1068
9         879             879               4   879
1         743             743               6   743
5         391             137               1   391
8         322             108               1   322
3         167             167               8   167
0          28              24               9    28

In [55]:
# Temp
df.groupby("cluster")[[
    "future_ret_1y",
    "future_ret_3y",
    "future_ret_5y"
]].median()

         future_ret_1y  future_ret_3y  future_ret_5y
cluster
0             0.231757      -0.699556      -0.740942
1             0.661578       0.392104       0.460432
2             0.617843       0.466138       0.627480
3             0.443333       0.266596       0.418009
4             0.267933       0.278887       0.512415
5             0.902198       2.062638       2.183823
6             0.719146       0.584055       0.948383
7             0.930522       0.681756       1.110636
8             0.118899       0.165902       0.242467
9             0.841937       0.597473       0.728630

In [56]:
# Look at cluster VS average overall
TARGET_COLS = [
    "future_ret_1d",
    "future_ret_1w",
    "future_ret_1m",
    "future_ret_6m",
    "future_ret_1y",
    "future_ret_3y",
    "future_ret_5y"
]

ID_COLS = ["ticker", "date", "sector"]

PRIM_EXCLUDE = {
    "price",
    "sector_size",
    "rows",
    "sector_size_market",
    "rows_market"
}

SEC_EXCLUDE = {
    "excess_ret_1y", "excess_ret_5y",
    "trend_vs_sector_1y", "trend_vs_sector_5y",
    "drawdown_rel_1y", "drawdown_rel_5y",
    "excess_vs_market_1y", "trend_vs_market_1y",
    "risk_adjusted_1y", "risk_adjusted_5y",
    "quality_score",
    "sector_Unknown"
}

numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()

numeric_cols.remove("cluster")

feature_cols = [
    c for c in numeric_cols
    if c not in (
        set(ID_COLS)
        | set(TARGET_COLS)
        | PRIM_EXCLUDE
        | SEC_EXCLUDE
    )
]

overall = df[feature_cols].mean()

cluster = df.groupby("cluster")[feature_cols].mean()

for c in cluster.index:
    print("\nCLUSTER", c)

    diff = (
        cluster.loc[c] - overall
    ).abs().sort_values(ascending=False)

    print(diff.head(15))

CLUSTER 0
pe                           28.897173
ret_5y                        3.145883
ret_3y                        1.933482
ret_1y                        1.573115
beta_1y                       1.389868
ret_6m                        1.352139
cluster_prob_0                0.996826
ret_1m                        0.675078
log_market_cap                0.456352
sector_Healthcare             0.300464
sector_Financial Services     0.278993
sec_ret_5y_dispersion         0.250645
cluster_prob_6                0.220746
ret_1w                        0.217910
cluster_prob_7                0.186449
dtype: float64

CLUSTER 1
pe                           9.388702
cluster_prob_1               0.914361
sec_ret_5y_dispersion        0.327846
sector_Technology            0.307774
sector_Financial Services    0.278993
sector_Healthcare            0.268307
log_market_cap               0.249038
cluster_prob_6               0.219315
ret_3y                       0.207321
ret_5y                       0.204457
sec_avg_ret_3y               0.190190
cluster_prob_7               0.186449
cluster_prob_2               0.185013
sec_avg_ret_5y               0.148770
beta_1y                      0.148245
dtype: float64

CLUSTER 2
pe                           1.163261
cluster_prob_2               0.814987
log_market_cap               0.325346
sec_ret_5y_dispersion        0.309946
sector_Financial Services    0.278993
cluster_prob_6               0.220746
cluster_prob_7               0.186449
sec_avg_ret_5y               0.174692
sec_avg_ret_3y               0.173719
ret_5y                       0.142697
ret_3y                       0.141986
sec_avg_ret_5y_market        0.133711
sec_avg_ret_3y_market        0.122570
cluster_prob_4               0.121075
beta_1y                      0.109127
dtype: float64

CLUSTER 3
pe                                90.275296
cluster_prob_3                     0.976397
ret_5y                             0.537796
beta_1y                            0.454935
ret_3y                             0.346946
sector_Financial Services          0.278993
cluster_prob_6                     0.220746
cluster_prob_2                     0.185013
cluster_prob_7                     0.181704
sec_ret_5y_dispersion              0.178310
log_market_cap                     0.171748
ret_1y                             0.143004
cluster_prob_4                     0.121075
sec_positive_5y_trend_pct          0.114833
sec_strong_drawdown_resilience     0.114435
dtype: float64

CLUSTER 4
pe                                2.246262
cluster_prob_4                    0.878925
sector_Financial Services         0.486924
log_market_cap                    0.302395
sec_ret_5y_dispersion             0.234547
sec_breadth_positive_5y           0.231113
cluster_prob_6                    0.220746
sec_strong_drawdown_resilience    0.211004
sec_positive_1y_trend_pct         0.204927
cluster_prob_7                    0.186449
cluster_prob_2                    0.185013
5y_drawdown                       0.162248
sec_avg_5y_drawdown               0.162151
beta_1y                           0.152477
1y_drawdown                       0.143277
dtype: float64

CLUSTER 5
pe                           19.571161
cluster_prob_5                0.955674
sector_Energy                 0.955561
beta_1y                       0.631830
sec_avg_ret_5y                0.628975
ret_5y                        0.615120
sec_avg_ret_3y                0.415981
ret_3y                        0.397910
sec_positive_1y_trend_pct     0.397060
sec_breadth_positive_5y       0.393875
sec_ret_5y_dispersion         0.393261
ret_1y                        0.310214
sec_avg_ret_1y                0.303874
sec_positive_5y_trend_pct     0.299536
sector_Financial Services     0.278993
dtype: float64

CLUSTER 6
pe                                  1.006405
cluster_prob_6                      0.778812
cluster_prob_7                      0.186449
cluster_prob_2                      0.185013
log_market_cap                      0.164290
sec_positive_1y_trend_pct           0.144357
sector_Financial Services           0.142167
ret_5y                              0.124344
cluster_prob_4                      0.121075
ret_3y                              0.118394
sec_positive_1y_trend_pct_market    0.114808
sector_Technology                   0.104070
sec_avg_ret_1w_market               0.103395
sec_avg_ret_3y                      0.100882
cluster_prob_9                      0.099649
dtype: float64

CLUSTER 7
pe                           2.737466
cluster_prob_7               0.813473
log_market_cap               0.351763
sector_Financial Services    0.221615
cluster_prob_6               0.220746
cluster_prob_2               0.185013
ret_5y                       0.167811
ret_3y                       0.156679
sec_ret_5y_dispersion        0.143534
sec_avg_ret_3y               0.133620
sector_Industrials           0.130371
sec_avg_ret_5y               0.130268
ret_1m                       0.123300
sec_avg_ret_1m               0.121534
cluster_prob_4               0.121075
dtype: float64

CLUSTER 8
pe                                13.589482
log_market_cap                     0.999387
sector_Utilities                   0.963496
cluster_prob_8                     0.963496
beta_1y                            0.383859
sec_breadth_positive_1y            0.375905
sec_breadth_positive_5y            0.373356
sec_ret_5y_dispersion              0.362159
sec_strong_drawdown_resilience     0.357941
ret_5y                             0.341748
sec_avg_ret_5y                     0.327532
sec_high_monotonic_pct             0.320925
sector_Financial Services          0.278993
sec_positive_1y_trend_pct          0.276011
ret_3y                             0.240483
dtype: float64

CLUSTER 9
pe                           9.747908
cluster_prob_9               0.900351
sector_Industrials           0.299663
sector_Financial Services    0.278993
sec_ret_5y_dispersion        0.237364
log_market_cap               0.230708
cluster_prob_6               0.220746
sector_Healthcare            0.199985
cluster_prob_7               0.186449
cluster_prob_2               0.185013
cluster_prob_4               0.121075
sector_Consumer Defensive    0.106306
sector_Technology            0.104070
sec_avg_ret_5y_market        0.096331
sec_avg_ret_3y_market        0.092287
dtype: float64

In [57]:
# Compare stock performance

cluster_performance = df.groupby("cluster").agg(
    stocks=("ticker","nunique"),
    rows=("ticker","count"),
    median_1y=("future_ret_1y","median"),
    median_3y=("future_ret_3y","median"),
    median_5y=("future_ret_5y","median"),
    positive_5y=("future_ret_5y", lambda x: (x > 0).mean())
)

cluster_performance.sort_values("median_5y", ascending=False)

         stocks  rows  median_1y  median_3y  median_5y  positive_5y
cluster
5           137   391   0.902198   2.062638   2.183823     0.966752
7          1644  1644   0.930522   0.681756   1.110636     0.897202
6          1947  1947   0.719146   0.584055   0.948383     0.872625
9           879   879   0.841937   0.597473   0.728630     0.757679
2          1632  1632   0.617843   0.466138   0.627480     0.726103
4          1068  1068   0.267933   0.278887   0.512415     0.852996
1           743   743   0.661578   0.392104   0.460432     0.686406
3           167   167   0.443333   0.266596   0.418009     0.748503
8           108   322   0.118899   0.165902   0.242467     0.717391
0            24    28   0.231757  -0.699556  -0.740942     0.285714

In [58]:
# Top 50 stocks in best cluster
best_cluster = BEST_CLUSTER

best = df[
    df["cluster"] == best_cluster
]

stocks = (
    best.groupby("ticker")
    .agg(
        observations=("ticker","count"),
        avg_future_5y=("future_ret_5y","mean"),
        median_future_5y=("future_ret_5y","median"),
        avg_return_1y=("future_ret_1y","mean"),
        avg_beta=("beta_1y","mean"),
        avg_market_cap=("log_market_cap","mean")
    )
    .sort_values(
        "median_future_5y",
        ascending=False
    )
)

stocks.head(50)

,observations,avg_future_5y,median_future_5y,avg_return_1y,avg_beta,avg_market_cap
ticker,,,,,,
BBW,1,34.611350,34.611350,4.983606,1.271453,16.362653
MOD,1,24.983607,24.983607,3.842623,1.437699,18.897462
DAC,1,23.277318,23.277318,11.953004,1.996217,17.875865
ESEA,1,21.489260,21.489260,3.658767,0.846318,16.022183
BXC,1,17.639902,17.639902,8.535279,1.738697,17.280798
DDS,1,15.049522,15.049522,2.508786,1.668915,19.330900
UAN,1,14.287739,14.287739,3.385871,2.401832,17.616078
HOV,1,13.967002,13.967002,14.170732,2.964760,17.380799
SAABF,1,13.529534,13.529534,0.586402,0.665450,21.020817
CMT,1,13.092592,13.092592,9.861110,0.792077,16.039957
LWAY,1,12.404372,12.404372,1.950820,1.123391,17.146495
DKS,1,12.223149,12.223149,3.385256,1.534393,20.700686
EAT,1,11.845083,11.845083,5.184508,2.594990,20.015575
RCMT,1,11.688000,11.688000,1.840000,0.962851,15.997003
STRL,1,11.666303,11.666303,1.529989,1.476339,19.455253
EMO,1,10.251748,10.251748,2.186538,2.870715,18.175515
BYDDF,1,9.972798,9.972798,3.509855,1.201913,22.469851
CRS,1,9.927257,9.927257,1.325665,2.114154,20.526118
BLDR,1,9.845819,9.845819,3.039199,2.030184,20.934165
LNWO,1,9.631264,9.631264,3.596659,2.571245,20.306516
GGAL,1,9.309493,9.309493,0.133587,2.033538,20.337894
IESC,1,9.187652,9.187652,2.081296,1.393523,19.602269
IDT,1,9.086220,9.086220,3.382978,1.732861,18.594606
BBAR,1,9.005306,9.005306,0.070588,1.748623,19.747912
TBBK,1,8.720888,8.720888,2.829945,2.223580,19.232687
SIG,1,8.661793,8.661793,8.102042,2.963814,19.280812
FIX,1,8.600711,8.600711,1.171784,1.580096,20.892135
GPI,1,8.473082,8.473082,2.865997,2.016494,19.967732
WSM,1,8.375283,8.375283,3.882583,1.837806,21.395404
ANF,1,8.372093,8.372093,3.199511,1.635330,19.709933
MMYT,1,8.071867,8.071867,1.767748,1.327964,20.745038
POWL,1,7.903431,7.903431,0.556249,1.746654,19.296273
SKT,1,7.867782,7.867782,2.431933,1.688705,19.825448
WLFC,1,7.719858,7.719858,1.317866,1.986055,18.791047
NMM,1,7.659473,7.659473,4.107709,1.693263,18.661562
LQDT,1,7.647382,7.647382,4.118457,1.006958,18.544560
VSEC,1,7.580072,7.580072,1.823355,1.685821,19.756091
PWR,1,7.362274,7.362274,1.870868,1.352697,22.239798
GSL,1,7.323656,7.323656,2.852459,1.691900,18.330982
TSLA,1,7.209257,7.209257,5.935065,1.748032,25.515528
RCL,1,7.120906,7.120906,2.322080,2.326013,22.628531
TATT,1,7.103448,7.103448,0.477011,0.891079,17.626194
MHO,1,7.092724,7.092724,3.213267,2.606988,19.698201
GRBK,1,6.811908,6.811908,2.069012,1.417189,19.580194
HRI,1,6.797250,6.797250,4.344409,2.658449,20.178363
PAM,1,6.467105,6.467105,0.394737,1.564231,20.164363
UNM,1,6.465956,6.465956,1.265169,2.321374,21.231865
DXPE,1,6.347518,6.347518,1.674645,1.990949,18.979724
CHCI,1,6.300000,6.300000,3.446154,1.039326,16.384350
SKY,1,6.242494,6.242494,2.484219,1.649408,20.385099

In [59]:
# Cluster stability

cluster_frequency = (
    df.groupby("ticker")["cluster"]
    .agg(
        lambda x: x.value_counts().index[0]
    )
)

cluster_frequency.value_counts()

best_stocks = cluster_frequency[
    cluster_frequency == best_cluster
]

best_stocks.head()

Series([], Name: cluster, dtype: int64)

In [60]:
# Winning cluster VS market

comparison = pd.DataFrame({
    "winning_cluster": df[df.cluster==best_cluster]["future_ret_5y"],
    "all_stocks": df["future_ret_5y"]
})

comparison.describe()

       winning_cluster   all_stocks
count      1947.000000  8821.000000
mean          1.454378     1.336341
std           2.168695     2.399808
min          -0.990833    -0.998295
25%           0.316991     0.158593
50%           0.948383     0.777199
75%           1.874903     1.710897
max          34.611350    43.518393