In [1]:
# Load cluster
import pandas as pd
import numpy as np

BEST_CLUSTER = 0

train_df = pd.read_parquet( "../logs/kmean/train_clustered_gen1.parquet" )

test_df = pd.read_parquet( "../logs/kmean/test_clustered_gen1.parquet" )

print( "(Rows, Columns)" )
print( "Train:", train_df.shape )
print( "Test:", test_df.shape )

(Rows, Columns)
Train: (500486, 116)
Test: (150912, 116)

In [2]:
def cluster_composition( df ):
    cluster_summary = df.groupby( "cluster" ).agg(
        rows=( "ticker", "count" ),
        unique_tickers=( "ticker", "nunique" ),
        unique_sectors=( "sector", "nunique" )
    )

    year_counts = (
        df.assign(year=df["date"].dt.year)
          .groupby(["cluster", "year"])
          .size()
          .unstack( fill_value=0 )
    )

    return cluster_summary.join( year_counts )


print( "TRAIN" )
train_cluster_summary = cluster_composition( train_df )
display( train_cluster_summary.sort_values( "rows", ascending=False ) )

print( "\nTEST" )
test_cluster_summary = cluster_composition( test_df )
display( test_cluster_summary.sort_values( "rows", ascending=False ) )

TRAIN

           rows  unique_tickers  unique_sectors   2016    2017   2018   2019
cluster
1        335161            2928              12  53050  109572  99330  73209
0        165325            2540              12  21695   39360  54105  50165

TEST

          rows  unique_tickers  unique_sectors   2020   2021
cluster
1        94469            2818              12  39697  54772
0        56443            2239              12  37654  18789

In [3]:
# Look at cluster VS average overall
TARGET_COLS = [
    # Absolute returns
    "future_ret_1d",
    "future_ret_1w",
    "future_ret_1m",
    "future_ret_6m",
    "future_ret_1y",
    "future_ret_3y",
    "future_ret_5y",

    # Relative returns
    "future_excess_1d",
    "future_excess_1w",
    "future_excess_1m",
    "future_excess_6m",
    "future_excess_1y",
    "future_excess_3y",
    "future_excess_5y"
]

ID_COLS = ["ticker", "date", "sector"]
JUNK_EXCLUDE = {
    "price",
    "sector_size",
    "rows",
    "sector_size_market",
    "rows_market"
}

SEC_EXCLUDE = {
    "sector_is_trending",

    "sec_avg_ret_1w",
    "sec_avg_ret_1m",
    "sec_avg_ret_6m",
    "sec_avg_ret_1y",
    "sec_avg_ret_3y",
    "sec_avg_ret_5y",

    "sec_avg_ret_1w_market",
    "sec_avg_ret_1m_market",
    "sec_avg_ret_6m_market",
    "sec_avg_ret_1y_market",
    "sec_avg_ret_3y_market",
    "sec_avg_ret_5y_market",

    "sec_positive_1y_trend_pct",
    "sec_positive_5y_trend_pct",
    "sec_breadth_positive_1y",
    "sec_breadth_positive_5y",

    "sec_ret_1y_dispersion",
    "sec_ret_5y_dispersion",
    "sec_ret_1y_dispersion_market",
    "sec_ret_5y_dispersion_market",

    "quality_score",
    "sector_Unknown",
}

OTHER_EXCLUDE = {
    "pe"
}

numeric_cols = train_df.select_dtypes( include=[np.number] ).columns.tolist()

numeric_cols.remove( "cluster" )

feature_cols = [
    c for c in numeric_cols
    if c not in ( set( ID_COLS ) | set( TARGET_COLS ) | JUNK_EXCLUDE | SEC_EXCLUDE | {c for c in train_df.columns if c.startswith("future_")} | OTHER_EXCLUDE )
]

overall = train_df[feature_cols].mean()

cluster = train_df.groupby("cluster")[feature_cols].mean()

print( "Comparison of cluster average to overall average, per feature")

for c in cluster.index:
    print("\nCLUSTER", c)

    diff = (
        cluster.loc[c] - overall
    ).sort_values(ascending=False)

    print(diff.head(15))

Comparison of cluster average to overall average, per feature

CLUSTER 0
beta_1y                          0.146941
sector_Energy                    0.038516
sector_Healthcare                0.027317
sector_Basic Materials           0.018808
sector_Consumer Cyclical         0.017408
sector_Technology                0.012874
sector_Communication Services    0.011979
spy_ret_3y                       0.007225
sector_Consumer Defensive        0.002988
sector_Industrials               0.000496
sec_avg_5y_trend_market         -0.000003
sec_avg_5y_trend                -0.000053
sec_avg_1y_trend_market         -0.000068
sec_avg_ret_1d_market           -0.000124
sec_avg_1y_trend                -0.000132
dtype: float64

CLUSTER 1
ret_5y                 0.399661
excess_ret_5y          0.385584
risk_adjusted_1y       0.362308
risk_adjusted_5y       0.316657
log_market_cap         0.240727
ret_3y                 0.221216
ret_1y                 0.139226
excess_ret_1y          0.133392
5y_drawdown            0.131116
excess_vs_market_1y    0.129386
drawdown_rel_5y        0.112148
monotonic_score        0.093302
1y_drawdown            0.076307
ret_6m                 0.071216
drawdown_rel_1y        0.064727
dtype: float64

In [4]:
print( "Comparison of features, cluster to cluster" )

feature_compare = train_df.groupby("cluster")[
    [
        "ret_1y",
        "ret_5y",
        "excess_ret_1y",
        "excess_ret_5y",
        "monotonic_score",
        "risk_adjusted_1y",
        "5y_drawdown"
    ]
].mean()

feature_compare

Comparison of features, cluster to cluster

,ret_1y,ret_5y,excess_ret_1y,excess_ret_5y,monotonic_score,risk_adjusted_1y,5y_drawdown
cluster,,,,,,,
0,-0.151186,-0.034544,-0.267255,-0.854343,0.430731,-0.772989,-0.514777
1,0.270291,1.175345,0.136561,0.312932,0.713183,0.323821,-0.117852

In [5]:
# Compare stock performance
def cluster_performance(df):
    return (
        df.groupby("cluster")
          .agg(
              stocks=("ticker", "nunique"),
              rows=("ticker", "count"),

              median_1y=("future_ret_1y", "median"),
              median_3y=("future_ret_3y", "median"),
              median_5y=("future_ret_5y", "median"),

              median_excess_1y=("future_excess_1y", "median"),
              median_excess_3y=("future_excess_3y", "median"),
              median_excess_5y=("future_excess_5y", "median"),

              positive_5y=("future_ret_5y", lambda x: (x > 0).mean()),
              beats_spy_5y=("future_excess_5y", lambda x: (x > 0).mean())
          )
          .sort_values("median_excess_5y", ascending=False)
    )

print("TRAIN")
cluster_performance(train_df)

TRAIN

,stocks,rows,median_1y,median_3y,median_5y,median_excess_1y,median_excess_3y,median_excess_5y,positive_5y,beats_spy_5y
cluster,,,,,,,,,,
1,2928,335161,0.052464,0.188439,0.298351,-0.072358,-0.303206,-0.572941,0.730974,0.219375
0,2540,165325,-0.006222,0.129932,0.184962,-0.130852,-0.396952,-0.690481,0.596262,0.247682

In [6]:
print("TEST")
cluster_performance(test_df)

TEST

,stocks,rows,median_1y,median_3y,median_5y,median_excess_1y,median_excess_3y,median_excess_5y,positive_5y,beats_spy_5y
cluster,,,,,,,,,,
0,2239,56443,0.297448,0.247923,0.642960,0.039125,-0.104295,-0.359617,0.742838,0.373917
1,2818,94469,0.080474,0.056357,0.288331,-0.088941,-0.281804,-0.648915,0.683049,0.232267

In [7]:
# Top 50 stocks in best cluster
def best_50( df ):

    best = df[
        df["cluster"] == BEST_CLUSTER
    ]

    stocks = (
        best.groupby("ticker")
        .agg(
            observations=("ticker","count"),
            avg_future_5y=("future_ret_5y","mean"),
            median_future_5y=("future_ret_5y","median"),
            avg_return_1y=("future_ret_1y","mean"),
            avg_beta=("beta_1y","mean"),
            avg_market_cap=("log_market_cap","mean")
        )
        .sort_values(
            "median_future_5y",
            ascending=False
        )
    )

    return stocks.head(50)

best_50( train_df )

,observations,avg_future_5y,median_future_5y,avg_return_1y,avg_beta,avg_market_cap
ticker,,,,,,
ENPH,30,159.823097,159.352897,2.341390,2.863870,19.305254
GRVY,27,26.492218,34.873605,2.739361,0.644872,17.415885
GMWKF,25,27.256269,30.108692,3.042369,-0.271555,18.795250
CYRX,39,22.785599,27.195980,2.234686,1.652005,18.707485
CHRD,151,24.492626,23.548472,3.123527,4.067695,19.441080
ARWR,65,19.713151,18.693694,2.945199,3.016333,19.730129
OPRX,59,16.018727,16.092263,1.357531,0.422459,17.773533
CAMT,12,15.153389,15.186893,0.997490,1.299086,18.483290
ATLC,115,15.396563,14.660633,0.307534,0.286459,17.442992
TSLA,46,11.587127,11.996891,3.131670,2.486679,24.871111
AMRC,44,11.599789,11.884624,0.603711,2.709711,19.060931
VCEL,73,12.467140,11.548275,1.872339,1.797609,18.832124
PAR,24,10.904970,11.112615,0.827730,1.433226,19.192008
BLDR,39,10.790256,11.108988,0.614374,2.681368,21.100337
AEHR,100,11.502626,10.949562,-0.086030,2.245656,17.937883
CROX,69,11.876629,10.573984,0.818791,2.506470,19.814830
LSCC,50,11.114767,10.568670,0.800393,1.754644,20.491856
ADTTF,42,10.053934,10.019840,1.283762,-0.068061,21.038434
LEU,148,11.068891,9.862038,0.470435,1.491173,18.002445
BLFS,24,8.889259,9.662087,2.614450,0.889328,18.450080
MTCH,13,9.351048,9.570297,0.268632,1.842245,21.928978
SMCI,133,15.134070,9.143137,0.081824,2.555210,20.994195
AMD,4,8.222694,8.581147,1.596700,3.396931,23.504346
PODD,1,8.442948,8.442948,0.697072,2.136606,21.444929
FTNT,22,8.487764,8.438720,0.231054,2.398300,22.281453
FLNA,147,10.572578,8.423215,0.962541,1.792748,18.742405
SANG,20,8.932809,8.208791,1.539116,0.642775,17.847209
FIX,10,7.945680,8.179490,0.328579,2.014727,21.033494
ZBRA,20,7.928338,7.567619,0.708680,2.802622,21.800834
DXCM,24,6.964496,7.083352,1.498642,2.334050,22.375123
APPS,89,11.186177,6.882682,1.551086,2.038685,18.979208
ACLS,66,6.464978,6.634288,0.219160,3.309168,20.129424
SAIA,41,6.737380,6.611801,0.627577,2.162580,21.032957
DRS,89,6.374731,5.996337,0.711121,1.548468,20.196838
GIC,68,4.268449,5.853383,1.363645,2.167596,19.456539
NSSC,1,5.825316,5.825316,0.754430,0.693927,18.722370
GNRC,24,5.956787,5.800623,0.375327,2.643234,21.486435
BXC,105,6.046798,5.664830,0.942481,2.034112,18.295543
CALX,137,6.371829,5.653901,0.372845,2.448079,19.868819
KLAC,2,5.635738,5.635738,1.069742,2.972501,23.037560
PERI,164,6.073943,5.561390,0.221831,1.981259,18.758171
QDEL,9,4.857108,5.397392,1.255557,1.939186,21.110059
GME,163,6.523668,5.341378,-0.205500,2.170426,21.175579
TRNS,1,5.338384,5.338384,0.262626,0.445502,18.342426
BX,20,5.197378,5.275807,0.436221,3.048121,23.240089
SMTI,138,5.182735,5.222667,0.651253,0.717170,17.763861
ATEYY,5,5.613458,5.209775,1.450686,1.111846,21.809763
AAPL,3,5.128432,5.112532,0.538342,1.732344,26.498392
NVMI,7,5.422557,5.055803,0.584405,2.095859,20.314797
KTOS,9,3.601009,4.997747,1.486242,2.577494,20.823968

In [8]:
best_50( test_df )

,observations,avg_future_5y,median_future_5y,avg_return_1y,avg_beta,avg_market_cap
ticker,,,,,,
CLS,43,36.721943,36.100372,0.292760,2.092602,20.607870
INOD,5,32.642156,33.242857,3.999420,0.270008,17.672562
ESEA,28,28.095871,27.793097,7.505833,0.992592,16.453539
MSTR,14,26.983148,24.061030,3.773354,1.043003,22.244467
STRL,6,23.644282,23.967354,1.128667,1.609173,19.584456
SMCI,1,21.386901,21.386901,0.596726,1.479714,21.129659
MOD,19,19.828779,19.615922,1.112459,1.822093,19.647190
BBW,33,19.585286,17.952930,4.311734,1.538552,17.400069
UAN,35,17.254756,17.847776,6.308177,2.223957,17.827069
DDS,28,17.954254,17.058412,5.096299,2.057385,19.660594
DAC,23,16.899779,16.544079,11.442055,2.075939,18.441992
AGX,7,14.073090,14.829790,-0.167892,1.333977,20.218802
SAABF,30,14.436089,13.868881,0.325690,0.535249,21.443419
AEHR,48,19.142800,13.357905,5.474252,1.347818,17.972042
GME,15,14.528250,13.064880,28.938486,1.346338,20.399027
RCMT,34,12.328955,12.942090,2.495780,1.199932,16.363466
FIX,2,12.696912,12.696912,0.964764,1.731046,21.033367
POWL,37,13.440711,12.328799,-0.017370,1.864970,19.534571
BELFB,40,12.841364,11.682410,0.057082,2.320722,18.847568
CRS,32,11.985651,11.546686,0.438076,2.370416,20.827646
NRP,33,10.732325,10.685104,1.365190,0.776568,18.588512
UEC,20,10.361044,10.613364,1.955685,1.853713,20.200202
BELFA,36,11.134429,10.241474,0.284404,1.225467,17.054460
CIEN,3,8.006362,9.487050,0.212640,1.252178,22.608562
EMBJ,41,8.835629,8.797276,1.440668,2.352066,20.866766
TRGP,30,8.451222,8.782664,1.535735,2.877228,22.077544
IDT,13,8.626225,8.621137,6.109887,1.641920,18.835076
EME,16,8.313569,8.192983,0.743565,1.450633,21.819303
HNRG,30,9.616114,8.097772,0.959709,0.365673,18.270693
TATT,50,7.621113,7.701523,0.324066,0.631152,17.948624
SM,31,7.722364,7.636467,8.141075,3.145459,20.426919
ARLP,43,8.656793,7.523896,1.845008,2.324424,19.606252
ATI,30,7.078850,7.267485,0.599163,2.311756,21.176660
CECO,43,7.106462,7.120000,-0.143457,2.071834,19.892130
YPF,51,7.109552,6.873418,-0.041432,1.970348,21.319735
ATLC,1,6.862353,6.862353,5.920000,1.994331,18.671463
TBBK,18,6.710310,6.841018,1.752474,2.450742,19.760297
FTI,49,6.577130,6.348785,0.083142,2.559558,21.696256
TPR,24,5.705859,6.173252,1.314913,2.252776,21.914508
MLI,9,6.010194,6.113734,0.555388,1.926279,21.801608
GSAT,30,6.995565,6.092024,3.204900,1.479501,20.417834
BMA,51,5.590282,6.066401,-0.009935,1.747065,20.383806
NMM,30,5.516212,6.055506,2.628512,1.617631,19.186823
GGAL,51,5.836935,6.024843,0.145561,1.798032,20.583986
EDN,51,6.070172,6.024631,0.585450,1.208437,18.147867
BBVA,33,6.258277,5.999689,0.816896,1.686717,23.425435
THC,19,6.177541,5.905315,1.718869,2.369716,21.527663
BBAR,51,5.655580,5.819154,0.086237,1.800741,19.949988
UUUU,20,6.947298,5.808572,2.994154,1.474485,19.865939
PBT,47,5.963288,5.793817,1.927552,1.218937,18.653530

In [9]:
# Cluster stability

cluster_frequency = (
    df.groupby("ticker")["cluster"]
    .agg(
        lambda x: x.value_counts().index[0]
    )
)

cluster_frequency.value_counts()

best_stocks = cluster_frequency[
    cluster_frequency == best_cluster
]

best_stocks.head()

NameError: name 'df' is not defined

In [ ]:
# Winning cluster VS market

comparison = pd.DataFrame({
    "winning_cluster": test_df[test_df.cluster==BEST_CLUSTER]["future_ret_5y"],
    "all_stocks": test_df["future_ret_5y"],
    "SPY": test_df[test_df.ticker == "SPY"]["future_ret_5y"]
})

print( "Comparison of returns" )
comparison.describe()

Comparison of returns

       winning_cluster     all_stocks        SPY
count     65598.000000  150912.000000  51.000000
mean          0.968448       0.797057   0.963987
std           2.135491       1.972052   0.116254
min          -0.999578      -0.999578   0.719934
25%          -0.003783      -0.084476   0.861662
50%           0.533836       0.401812   0.968480
75%           1.296885       1.108734   1.057251
max          53.853503      55.104512   1.177245